name: agile_prototyp
description: Prototype for agile Project

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.2
  dropdown_button2: ^1.4.0
  cupertino_icons: ^1.0.2
  connectivity_plus: ^2.3.6+1
  fluttertoast: ^8.0.9
  data_table_2: ^2.2.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  universal_html: ^2.0.8
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  flutter_launcher_icons: ^0.10.0
  json_annotation: ^4.7.0
  hive_generator: ^1.1.3
  intl: ^0.17.0
  http: ^0.13.5
  rflutter_alert: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.4.1
  build_runner: ^2.2.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/icon_adaptive_fore.png"
  adaptive_icon_background: "assets/icon_adaptive_back.png"